# Generated by Django 5.0.4 on 2024-05-30 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_customer_store_cutom_last_na_723f5c_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='customer',
            name='store_cutom_last_na_723f5c_idx',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='first_name',
            new_name='given_name',
        ),
        migrations.AlterModelTable(
            name='customer',
            table=None,
        ),
    ]
